version: 2

builds:
  - main: ./cmd/release-test
    binary: release-test
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
