name: Auto Tag

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  auto-tag:
    uses: ./.github/workflows/go-auto-tag.yml
    permissions:
      contents: write
      pull-requests: read
    with:
      default-bump: patch
