name: "Test: ts-ci.yml"

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/ts-ci.yml"
      - ".github/workflows/test-ts-ci.yml"
      - "_test-fixtures/ts-minimal/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/ts-ci.yml"
      - ".github/workflows/test-ts-ci.yml"
      - "_test-fixtures/ts-minimal/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  call-ts-ci-defaults:
    name: Call ts-ci (defaults)
    timeout-minutes: 20
    uses: ./.github/workflows/ts-ci.yml
    permissions:
      contents: read
    with:
      working-directory: _test-fixtures/ts-minimal

  call-ts-ci-test-only:
    name: Call ts-ci (test only, no lint/typecheck)
    timeout-minutes: 20
    uses: ./.github/workflows/ts-ci.yml
    permissions:
      contents: read
    with:
      working-directory: _test-fixtures/ts-minimal
      enable-typecheck: false
      enable-lint: false
